/*
 * This file is generated by jOOQ.
 */
package github.clyoudu.order.jooq.tables;


import github.clyoudu.order.jooq.Indexes;
import github.clyoudu.order.jooq.Keys;
import github.clyoudu.order.jooq.OrderDb;
import github.clyoudu.order.jooq.tables.records.OrderTbRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderTb extends TableImpl<OrderTbRecord> {

    private static final long serialVersionUID = -923986926;

    /**
     * The reference instance of <code>order_db.order_tb</code>
     */
    public static final OrderTb ORDER_TB = new OrderTb();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderTbRecord> getRecordType() {
        return OrderTbRecord.class;
    }

    /**
     * The column <code>order_db.order_tb.id</code>.
     */
    public final TableField<OrderTbRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>order_db.order_tb.user_name</code>.
     */
    public final TableField<OrderTbRecord, String> USER_NAME = createField("user_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>order_db.order_tb.product_code</code>.
     */
    public final TableField<OrderTbRecord, String> PRODUCT_CODE = createField("product_code", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>order_db.order_tb.count</code>.
     */
    public final TableField<OrderTbRecord, Integer> COUNT = createField("count", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>order_db.order_tb</code> table reference
     */
    public OrderTb() {
        this(DSL.name("order_tb"), null);
    }

    /**
     * Create an aliased <code>order_db.order_tb</code> table reference
     */
    public OrderTb(String alias) {
        this(DSL.name(alias), ORDER_TB);
    }

    /**
     * Create an aliased <code>order_db.order_tb</code> table reference
     */
    public OrderTb(Name alias) {
        this(alias, ORDER_TB);
    }

    private OrderTb(Name alias, Table<OrderTbRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrderTb(Name alias, Table<OrderTbRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> OrderTb(Table<O> child, ForeignKey<O, OrderTbRecord> key) {
        super(child, key, ORDER_TB);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return OrderDb.ORDER_DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ORDER_TB_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OrderTbRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ORDER_TB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OrderTbRecord> getPrimaryKey() {
        return Keys.KEY_ORDER_TB_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OrderTbRecord>> getKeys() {
        return Arrays.<UniqueKey<OrderTbRecord>>asList(Keys.KEY_ORDER_TB_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderTb as(String alias) {
        return new OrderTb(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderTb as(Name alias) {
        return new OrderTb(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderTb rename(String name) {
        return new OrderTb(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderTb rename(Name name) {
        return new OrderTb(name, null);
    }
}
