/*
 * This file is generated by jOOQ.
 */
package github.clyoudu.storage.jooq.tables.records;


import github.clyoudu.storage.jooq.tables.StockTb;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StockTbRecord extends UpdatableRecordImpl<StockTbRecord> implements Record7<Integer, String, String, String, BigDecimal, Integer, String> {

    private static final long serialVersionUID = -61630116;

    /**
     * Setter for <code>stock_db.stock_tb.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>stock_db.stock_tb.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stock_db.stock_tb.product_code</code>.
     */
    public void setProductCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>stock_db.stock_tb.product_code</code>.
     */
    public String getProductCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>stock_db.stock_tb.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stock_db.stock_tb.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>stock_db.stock_tb.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stock_db.stock_tb.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stock_db.stock_tb.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>stock_db.stock_tb.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>stock_db.stock_tb.count</code>.
     */
    public void setCount(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>stock_db.stock_tb.count</code>.
     */
    public Integer getCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>stock_db.stock_tb.user_name</code>.
     */
    public void setUserName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>stock_db.stock_tb.user_name</code>.
     */
    public String getUserName() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, BigDecimal, Integer, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, BigDecimal, Integer, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return StockTb.STOCK_TB.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return StockTb.STOCK_TB.PRODUCT_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return StockTb.STOCK_TB.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return StockTb.STOCK_TB.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return StockTb.STOCK_TB.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return StockTb.STOCK_TB.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return StockTb.STOCK_TB.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getProductCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProductCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockTbRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockTbRecord value2(String value) {
        setProductCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockTbRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockTbRecord value4(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockTbRecord value5(BigDecimal value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockTbRecord value6(Integer value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockTbRecord value7(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockTbRecord values(Integer value1, String value2, String value3, String value4, BigDecimal value5, Integer value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StockTbRecord
     */
    public StockTbRecord() {
        super(StockTb.STOCK_TB);
    }

    /**
     * Create a detached, initialised StockTbRecord
     */
    public StockTbRecord(Integer id, String productCode, String name, String description, BigDecimal price, Integer count, String userName) {
        super(StockTb.STOCK_TB);

        set(0, id);
        set(1, productCode);
        set(2, name);
        set(3, description);
        set(4, price);
        set(5, count);
        set(6, userName);
    }
}
