/*
 * This file is generated by jOOQ.
 */
package github.clyoudu.storage.jooq;


import github.clyoudu.storage.jooq.tables.StockTb;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StockDb extends SchemaImpl {

    private static final long serialVersionUID = -1063853178;

    /**
     * The reference instance of <code>stock_db</code>
     */
    public static final StockDb STOCK_DB = new StockDb();

    /**
     * The table <code>stock_db.stock_tb</code>.
     */
    public final StockTb STOCK_TB = github.clyoudu.storage.jooq.tables.StockTb.STOCK_TB;

    /**
     * No further instances allowed
     */
    private StockDb() {
        super("stock_db", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            StockTb.STOCK_TB);
    }
}
