/*
 * This file is generated by jOOQ.
 */
package github.clyoudu.storage.jooq;


import github.clyoudu.storage.jooq.tables.StockTb;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in stock_db
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>stock_db.stock_tb</code>.
     */
    public static final StockTb STOCK_TB = github.clyoudu.storage.jooq.tables.StockTb.STOCK_TB;
}
