/*
 * This file is generated by jOOQ.
 */
package github.clyoudu.order.jooq;


import github.clyoudu.order.jooq.tables.OrderTb;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>order_db</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ORDER_TB_PRIMARY = Indexes0.ORDER_TB_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ORDER_TB_PRIMARY = Internal.createIndex("PRIMARY", OrderTb.ORDER_TB, new OrderField[] { OrderTb.ORDER_TB.ID }, true);
    }
}
