/*
 * This file is generated by jOOQ.
 */
package github.clyoudu.order.jooq;


import github.clyoudu.order.jooq.tables.OrderTb;
import github.clyoudu.order.jooq.tables.records.OrderTbRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>order_db</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<OrderTbRecord, Integer> IDENTITY_ORDER_TB = Identities0.IDENTITY_ORDER_TB;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<OrderTbRecord> KEY_ORDER_TB_PRIMARY = UniqueKeys0.KEY_ORDER_TB_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<OrderTbRecord, Integer> IDENTITY_ORDER_TB = Internal.createIdentity(OrderTb.ORDER_TB, OrderTb.ORDER_TB.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<OrderTbRecord> KEY_ORDER_TB_PRIMARY = Internal.createUniqueKey(OrderTb.ORDER_TB, "KEY_order_tb_PRIMARY", OrderTb.ORDER_TB.ID);
    }
}
