/*
 * This file is generated by jOOQ.
 */
package github.clyoudu.order.jooq;


import github.clyoudu.order.jooq.tables.OrderTb;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderDb extends SchemaImpl {

    private static final long serialVersionUID = -231428227;

    /**
     * The reference instance of <code>order_db</code>
     */
    public static final OrderDb ORDER_DB = new OrderDb();

    /**
     * The table <code>order_db.order_tb</code>.
     */
    public final OrderTb ORDER_TB = github.clyoudu.order.jooq.tables.OrderTb.ORDER_TB;

    /**
     * No further instances allowed
     */
    private OrderDb() {
        super("order_db", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            OrderTb.ORDER_TB);
    }
}
