/*
 * This file is generated by jOOQ.
 */
package github.clyoudu.order.jooq;


import github.clyoudu.order.jooq.tables.OrderTb;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in order_db
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>order_db.order_tb</code>.
     */
    public static final OrderTb ORDER_TB = github.clyoudu.order.jooq.tables.OrderTb.ORDER_TB;
}
