/*
 * This file is generated by jOOQ.
 */
package github.clyoudu.account.jooq;


import github.clyoudu.account.jooq.tables.BalanceTb;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BalanceDb extends SchemaImpl {

    private static final long serialVersionUID = -1825599004;

    /**
     * The reference instance of <code>balance_db</code>
     */
    public static final BalanceDb BALANCE_DB = new BalanceDb();

    /**
     * The table <code>balance_db.balance_tb</code>.
     */
    public final BalanceTb BALANCE_TB = github.clyoudu.account.jooq.tables.BalanceTb.BALANCE_TB;

    /**
     * No further instances allowed
     */
    private BalanceDb() {
        super("balance_db", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            BalanceTb.BALANCE_TB);
    }
}
