/*
 * This file is generated by jOOQ.
 */
package github.clyoudu.account.jooq;


import github.clyoudu.account.jooq.tables.BalanceTb;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in balance_db
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>balance_db.balance_tb</code>.
     */
    public static final BalanceTb BALANCE_TB = github.clyoudu.account.jooq.tables.BalanceTb.BALANCE_TB;
}
